settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: trmusic.ir # unique identifier
    name: TRMusic
    description: 'Enjoy Music' # default=empty
    url: 'https://trmusic.ir/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: khoymusic.ir
    name: www.khoymusic.ir
    description: 'Download Music'
    url: 'https://khoymusic.ir/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Aalma.ir
    name: Aalma Magazine
    url: 'https://aalma.ir/'
    method: GET
    expectStatus: 200
